---
title: "Piru Enhancement - data preparation"
author: "Shane Dewees"
date: "2022-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here) # similar to set working directory
library(tidyverse) # data wrangling
library(lubridate) # dates and times
```

```{r mafa_cover, include=TRUE}
mafa_cover <- read.csv(here("data", "mafa_cover.csv")) %>%
  # filter(plot_type == "enhancement") %>% # removed this column
  select(date, plot_number, MAFA_removal, cover_type, cover_percent) %>% 
  # rename(cover_percent = cover_.) %>% 
  mutate(date = mdy(date),
         month = month(date),
         year = year(date)) %>% 
  filter(cover_type %in% c("MAFA", "MAFA alive")) 

print(mafa_cover)

mafa_cover_dates <- mafa_cover %>% 
  group_by(year, month) %>% 
 dplyr::summarize(mafa_cover_dates = n_distinct(year))

print(mafa_cover_dates)
# two monitoring dates: Fall 2017 and spring/summer 2019
# each monitoring event spanned two months 
```

```{r survivial, include=TRUE} 
survival <- read.csv(here("data", "survival_data.csv")) %>% 
  select(date, plot_number, MAFA_removal, species, alive) %>% 
  mutate(date = mdy(date),
         month = month(date),
         year = year(date)) %>% 
  group_by(year, month, plot_number, MAFA_removal, species) %>% 
  summarise(alive = sum(alive, na.rm = TRUE)) %>% 
    ungroup()

print(survival) # will only print the first 100 pages
# view(survival) # full data set for 2018-2021 here

survival_dates <- survival %>% 
  group_by(year, month) %>% 
 dplyr::summarize(survival_dates = n_distinct(year))

print(survival_dates)
```

```{r mortality, include=TRUE}
mortality <- read.csv(here("data", "survival_data.csv")) %>% 
  select(date, plot_number, MAFA_removal, species, dead) %>% 
  mutate(date = mdy(date),
         month = month(date),
         year = year(date)) %>% 
  group_by(year, month, plot_number, MAFA_removal, species) %>% 
  summarise(dead = sum(dead, na.rm = TRUE)) %>% 
    ungroup()

print(mortality)
# mortality is the inverse of survival

mortality_dates <- mortality %>% 
  group_by(year, month) %>% 
 dplyr::summarize(mortality_dates = n_distinct(year))

print(mortality_dates)
# mortality_dates should be the same as survival_dates
```

```{r par, include=TRUE}
par <- read.csv(here("data", "par_data.csv")) %>% 
  select(date, plot, weeding, readingno, ambient_PAR_1, below_PAR_1) %>% 
  rename(plot_number = plot) %>% 
  rename(treatment = weeding) %>% 
  mutate(date = case_when(date == "Jan. 30, 2019"~"1/30/2019",
                          date == "25-Jan-19"~"1/25/2019",
                          date == "24-Mar-19"~"3/24/2019",
                          date == "Nov. 16, 2019" ~ "11/16/2019",
                          date == "9-Sep-19" ~ "9/09/2019",
                          date == "19-Jul-19"~ "7/19/2019",
                          date == "24-May-19" ~ "5/24/2019",
                          TRUE ~ date),
         plot_number = str_remove(plot_number, "ENH0"),
         plot_number = str_remove(plot_number, "ENH"),
         plot_number = as.numeric(plot_number),
         treatment = str_remove(treatment, "removal"),
         date = mdy(date)) %>% 
  group_by(date, plot_number, treatment) %>% 
  summarize(ambient_par = mean(ambient_PAR_1),
            below_par = mean(below_PAR_1)) %>% 
  ungroup() %>% 
  mutate(normalized_par = below_par/ambient_par,
         month = month(date),
         year = year(date)) %>% 
  select(year, month, plot_number, treatment, normalized_par) 

print(par)

par_dates <- par %>% 
  group_by(year, month) %>% 
 dplyr::summarize(par_dates = n_distinct(year))

print(par_dates)
```


```{r tdr, include=TRUE}
tdr <- read.csv(here("data", "tdr_data.csv")) %>% 
  select(date, plot, TDR.value) %>% 
  rename(plot_number = plot,
         soil_moisture = TDR.value) %>% 
  mutate(plot_number = str_remove(plot_number, "ENH0"),
         plot_number = str_remove(plot_number, "ENH"),
         plot_number = as.numeric(plot_number),
         date = dmy(date)) %>% 
  group_by(date, plot_number) %>% 
  summarize(soil_moisture = mean(soil_moisture, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  select(!date) %>% 
  select(year, month, plot_number, soil_moisture)

print(tdr)

tdr_dates <- tdr %>% 
  group_by(year, month) %>% 
 dplyr::summarize(tdr_dates = n_distinct(year))

print(tdr_dates)
```

```{r survival_soil_moisture, include=TRUE}
survival_soil_moisture <- survival %>% 
  left_join(tdr, by = c("month", "year", "plot_number")) %>% 
  drop_na()

print(survival_soil_moisture)
```

```{r par_mafacover join, include=TRUE}
par_mafacover <- par %>% 
  filter(year == "2019") %>% 
  left_join(mafa_cover, by = c("plot_number")) %>% 
  drop_na() 

print(par_mafacover)
```