---
title: "leaftraits"
author: "Stephanie Ma Lucero"
date: "2023-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, include=FALSE}

library(here) # similar to set working directory
library(dplyr) # includes functions:
library(tidyverse) # data wrangling, includes packages: ggplot2, tibble, tidyr, rear, purrr, stringr, forcats
library(vegan)
library(plotly)
```

```{r}
remotes::install_github("gavinsimpson/ggvegan")
remotes::install_github("jfq3/ggordiplots")

#loading libraries
library(ggvegan)
library(tidyverse)
library(vegan)
library(ggpubr)
library(plotly)
library(ggordiplots)
```

```{r load data, include=FALSE}

leaftraits_load <- read_csv("data/leaftraits_2023.csv", 
                            col_types = cols(
                              species = col_character(), 
                              individual_ID = col_character(),
                                leaf_number = col_character(),
                              plant_rep = col_character(),
                              leaf_rep = col_character(),
                                area_m2 = col_number(),
                                SLA_m2kg = col_number(),
                                leaf_LDMC_proportion = col_number(),
                                leaf_LDMC_percent = col_number(),
                                leaf_thickness_check_cm = col_number()
                            ))

leaftraits <- leaftraits_load %>% 
  dplyr::select(species, individual_ID, leaf_number, plant_rep, leaf_rep, area_m2, SLA_m2kg, leaf_LDMC_proportion, leaf_LDMC_percent, leaf_thickness_check_cm) %>% 
  rename(leaf_thickness_cm = leaf_thickness_check_cm)

glimpse(leaftraits)
```
# LEAF TRAITS
### 1) SLA
```{r sla, include=TRUE}

ggplot(data = leaftraits, aes(y = SLA_m2kg, x = species, color = individual_ID)) + 
  geom_jitter()

print(TukeyHSD(aov(SLA_m2kg ~ individual_ID, data = leaftraits %>%  filter(species =="HEAR")))) # leaf sla is similar between individuals
print(TukeyHSD(aov(SLA_m2kg ~ individual_ID, data = leaftraits %>%  filter(species =="SAAP")))) # leaf sla is similar between individuals
print(TukeyHSD(aov(SLA_m2kg ~ individual_ID, data = leaftraits %>%  filter(species =="CEOL")))) # leaf sla is similar between individuals
print(TukeyHSD(aov(SLA_m2kg ~ individual_ID, data = leaftraits %>%  filter(species =="RHOV")))) # leaf sla is NOT similar between RHOV individuals
#$individual_ID
#                     diff         lwr         upr     p adj
#rhov-2-rhov-12 -1.7328279 -3.95462970  0.48897384 0.1488349
#rhov-6-rhov-12 -2.2332392 -4.45504100 -0.01143746 0.0486974 <-- 6 and 12
#rhov-9-rhov-12  0.5112162 -1.71058554  2.73301800 0.9015383
#rhov-6-rhov-2  -0.5004113 -2.72221307  1.72139047 0.9068663
#rhov-9-rhov-2   2.2440442  0.02224239  4.46584593 0.0474970 <-- 2 and 9
#rhov-9-rhov-6   2.7444555  0.52265369  4.96625723 0.0147640 <-- 6 and 9

# highlight all and run as one command
SLA <- aov(SLA_m2kg ~ species, data = leaftraits)
print(summary(SLA))
print(TukeyHSD(SLA))
#Fit: aov(formula = SLA_m2kg ~ species, data = leaftraits)
#
#$species
#                 diff        lwr       upr     p adj
#HEAR-CEOL -11.5090543 -14.957473 -8.060635 0.0000000
#RHOV-CEOL -12.4806143 -15.929033 -9.032195 0.0000000
#SAAP-CEOL   0.2182394  -3.230180  3.666659 0.9983177
#RHOV-HEAR  -0.9715599  -4.419979  2.476859 0.8786382
#SAAP-HEAR  11.7272937   8.278875 15.175713 0.0000000
#SAAP-RHOV  12.6988537   9.250435 16.147273 0.0000000
leaftraits %>%  
  group_by(species) %>% 
  summarize(avg_SLA_m2kg = mean(SLA_m2kg), 
            SD = sd(SLA_m2kg),
            N = length(SLA_m2kg), 
            SE = ((sd(SLA_m2kg))/sqrt(length((SLA_m2kg)))))
#species   avg_SLA_m2kg   SD   SE
#CEOL	18.091779	4.349259	16	1.0873148
#HEAR	6.582725	1.168144	16	0.2920359
#RHOV	5.611165	1.578581	16	0.3946452
#SAAP	18.310019	5.632231	16	1.4080577
```
### 2) LDMC 
```{r ldmc, include=TRUE}

ggplot(data = leaftraits, aes(y = leaf_LDMC_proportion, x = species, color = individual_ID)) + 
  geom_jitter()

print(TukeyHSD(aov(leaf_LDMC_proportion ~ individual_ID, data = leaftraits %>%  filter(species =="HEAR")))) # ldmc is not similar
#$individual_ID
#              diff          lwr          upr     p adj
#H2-H1  0.054775069  0.028450382  0.081099756 0.0002401 <-- 1 and 2
#H4-H1  0.030006824  0.003682137  0.056331510 0.0242512 <-- 1 and 4
#H3-H2 -0.058831491 -0.085156178 -0.032506805 0.0001230 <-- 3 and 2
#H4-H3  0.034063246  0.007738560  0.060387933 0.0108842 <-- 3 and 4
print(TukeyHSD(aov(leaf_LDMC_proportion ~ individual_ID, data = leaftraits %>%  filter(species =="SAAP")))) # leaf ldmc is not similar
#$individual_ID
#              diff         lwr          upr     p adj
#S5-S2 -0.081518376 -0.15076894 -0.012267814 0.0199746 <-- 5 and 2
#S5-S4 -0.074509568 -0.14376013 -0.005259006 0.0338004 <-- 5 and 4
print(TukeyHSD(aov(leaf_LDMC_proportion ~ individual_ID, data = leaftraits %>%  filter(species =="CEOL")))) # leaf ldmc is similar between individuals
print(TukeyHSD(aov(leaf_LDMC_proportion ~ individual_ID, data = leaftraits %>%  filter(species =="RHOV")))) # RHOV 9 and 2 are not the same

# highlight all and run as one command
LDMC <- aov(leaf_LDMC_proportion ~ species, data = leaftraits)
print(summary(LDMC))
print(TukeyHSD(LDMC))
#$species
#                 diff         lwr         upr     p adj
#HEAR-CEOL  0.09737519  0.05330571  0.14144467 0.0000013
#RHOV-CEOL  0.01199786 -0.03207162  0.05606734 0.8889855
#SAAP-CEOL -0.15750868 -0.20157817 -0.11343920 0.0000000
#RHOV-HEAR -0.08537733 -0.12944681 -0.04130785 0.0000200
#SAAP-HEAR -0.25488387 -0.29895335 -0.21081439 0.0000000
#SAAP-RHOV -0.16950654 -0.21357602 -0.12543706 0.0000000

leaftraits %>%  
  group_by(species) %>% 
  summarize(avg_LDMC_proportion = mean(leaf_LDMC_proportion), 
            SD = sd(leaf_LDMC_proportion),
            N = length(leaf_LDMC_proportion), 
            SE = ((sd(leaf_LDMC_proportion))/sqrt(length((leaf_LDMC_proportion)))))
#species   avg_SLA_m2kg   SD   SE
#CEOL	0.3679030	0.05064632	16	0.012661580
#HEAR	0.4652782	0.02712806	16	0.006782015
#RHOV	0.3799009	0.05837196	16	0.014592990
#SAAP	0.2103944	0.04681571	16	0.011703927
```
### 3) leaf thickness  
```{r leaf thickness, include=TRUE}

ggplot(data = leaftraits, aes(y = leaf_thickness_cm, x = species, color = individual_ID)) + 
  geom_jitter()

print(TukeyHSD(aov(leaf_thickness_cm ~ individual_ID, data = leaftraits %>%  filter(species =="HEAR")))) # leaf thickness is similar among leaves
print(TukeyHSD(aov(leaf_thickness_cm ~ individual_ID, data = leaftraits %>%  filter(species =="SAAP")))) # leaf thickness is not similar among the four leaves
#$individual_ID
#          diff           lwr         upr     p adj
#S4-S2  0.00900  0.0021035594 0.015896441 0.0102785 <-- 4 and 2
#S5-S2  0.00775  0.0008535594 0.014646441 0.0263699 <-- 2 and 5 
#S4-S3  0.00725  0.0003535594 0.014146441 0.0384030 <-- 4 and 3
print(TukeyHSD(aov(leaf_thickness_cm ~ individual_ID, data = leaftraits %>%  filter(species =="CEOL")))) # leaf thickness is similar among leaves
print(TukeyHSD(aov(leaf_thickness_cm ~ individual_ID, data = leaftraits %>%  filter(species =="RHOV")))) # leaf thickness is not similar among the four leaves
#rhov-9-rhov-2  -0.01275 -0.022624665 -0.0028753349 0.0110423 <-- 9 and 2
#rhov-9-rhov-6  -0.01075 -0.020624665 -0.0008753349 0.0316464 <-- 9 and 6

# highlight all and run as one command
Lt <- aov(leaf_thickness_cm ~ species, data = leaftraits)
print(summary(Lt))
print(TukeyHSD(Lt))
#$species
#                diff          lwr           upr     p adj
#HEAR-CEOL  0.0171875  0.011825429  0.0225495706 0.0000000
#RHOV-CEOL  0.0356250  0.030262929  0.0409870706 0.0000000
#SAAP-CEOL  0.0119375  0.006575429  0.0172995706 0.0000011
#RHOV-HEAR  0.0184375  0.013075429  0.0237995706 0.0000000
#SAAP-HEAR -0.0052500 -0.010612071  0.0001120706 0.0571111
#SAAP-RHOV -0.0236875 -0.029049571 -0.0183254294 0.0000000
leaftraits %>%  
  group_by(species) %>% 
  summarize(avg_Leafthickness_cm = mean(leaf_thickness_cm), 
            SD = sd(leaf_thickness_cm),
            N = length(leaf_thickness_cm), 
            SE = ((sd(leaf_thickness_cm))/sqrt(length((leaf_thickness_cm)))))
#species   avg_SLA_m2kg   SD   SE
#CEOL	0.0161875	0.004593020	16	0.0011482550
#HEAR	0.0333750	0.003947573	16	0.0009868933
#RHOV	0.0518125	0.008416007	16	0.0021040016
#SAAP	0.0281250	0.004924429	16	0.0012311072
```

# LIGHT CURVES
```{r load light curve data, include=FALSE}

par <- read_csv("data/par_data.csv")

par %>%  
  group_by(weeding) %>% 
  summarize(below_min = min(below_PAR_1), 
            below_mean = mean(below_PAR_1),
            below_median = median(below_PAR_1),
            below_max = max(below_PAR_1),
            amb_min = min(ambient_PAR_1), 
            amb_mean = mean(ambient_PAR_1),
            amb_max = max(ambient_PAR_1)
       )
# below_min    below_mean    below_max
# 25	          495.5538	    1384	

# amb_min      amb_mean      amb_max
# 361	          1267.144	    1764

# Light curve levels: 0, 25, 50, 100, 250, 500,  1000, 2000
par.scatter <- ggplot(data = par, 
                       aes(x = below_PAR_1, y = ambient_PAR_1)) +
  geom_point(aes(color = (weeding))) 
ggplotly(par.scatter)

# calculate mean photo based on 1000 PAR, which is closest to max PAR experienced by seedlings.

# calculate mean photo based on 500 PAR, which is the mean PAR experienced by seedlings.

# calculate mean photo based on 250 PAR, which is close to the min PAR experienced by seedlings.

```


# DROUGHT
```{r}

```


# NMDS
```{r data prep nmds, include=TRUE}
#non-metric multidimensional scaling

# # I DID THIS BECUASE I THOUGHT I NEEDD TO TRANSFORM THE DATAFRAME BUT I DIDN'T
# species or plant_reps in columns down
# observations or leaftrait data in rows across
# 
# leaftraits_nmdsprep_wide <- leaftraits %>% # data needed for NMDS. columns: species, plant_rep, sla, dlmc, leaf thickness
#    mutate(species_rep = paste(species, plant_rep, sep = "_")) %>%
#    mutate(species_rep_leaf = paste(species_rep, leaf_rep, sep = "_")) %>%
#  select(c(species_rep_leaf, SLA_m2kg, leaf_LDMC_proportion, leaf_thickness_cm))
# view(leaftraits_nmdsprep_wide)
# 
# # transforming data from wide to long - columns species_rep_leaf, LeafTrait, and values
# leaftraits_nmdsprep_long <- leaftraits_nmdsprep_wide %>%
#  pivot_longer(cols = c(SLA_m2kg, leaf_LDMC_proportion, leaf_thickness_cm),
#               names_to = "LeafTrait",
#               values_to = "value")
# 
# # spreading data for nmds
# leaftraits_nmdsprep <- leaftraits_nmdsprep_long %>%
#  tidyr::spread(species_rep_leaf, value)
# view(leaftraits_nmdsprep)
# 
# leaftraits_nmdsprep_num <- leaftraits_nmdsprep %>% # numeric only data needed for NMDS
#  select(!c(LeafTrait))

## END UNNEEDED CODE

leaftraits_nmdsprep <- leaftraits %>% # data needed for NMDS. columns: species, plant_rep, sla, dlmc, leaf thickness
    mutate(species_rep = paste(species, plant_rep, sep = "_")) %>% 
    mutate(species_rep_leaf = paste(species_rep, leaf_rep, sep = "_")) %>% 
  select(c(species_rep_leaf, SLA_m2kg, leaf_LDMC_proportion, leaf_thickness_cm)) 
view(leaftraits_nmdsprep)
  
  
# numbers only
leaftraits_nmdsprep_num <- leaftraits_nmdsprep %>% # numeric only data needed for NMDS
 select(!c(species_rep_leaf))

view(leaftraits_nmdsprep_num) # only numbers
str(leaftraits_nmdsprep_num)

#write.csv(leaftraits_nmdsprep_num, "~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/Ch3_piru_enhancement_Git/data/leaftraits_nmds.csv")

```

```{r nmds by leaf traits}

# OPTION 1: AUTOTRANSFORM
# caption: Uses Bray-Curtis distance to calculate NMDS. Using data ‘as is’. (autotransform = F)
# the AUTOTRANSFORM = F skips the automatic data transformations and uses the input data as is
# - when the raw data contains the information you need (e.g., abundance)
# - when you have a small number of samples or small number of variables
# - when you want to preserve the original scale of the data (e.g., interested in the absolute differences between two sets of measurements)
leaftraits_NMDS <- metaMDS(leaftraits_nmdsprep_num, autotransform = F) # this is more appropriate for my data

# OPTION 2: RAUP-CRICK
# uses the RAUP-CRICK dissimilarity index to calculate pairwise dissimilarities
# - adjusts for spp richness
# - downweights importance of rare spp 
# - more useful when interested in community STRUCTURE rather than individual species
# - takes into account differences in species evenness
# abcover_byspecies_NMDS <- metaMDS(abcover_byspecies_nmdsprep_num, distance = "raup") 


plot(leaftraits_NMDS)
```

```{r scores nmds}
scores(leaftraits_NMDS)
```

```{r stress plot nmds}
stressplot(leaftraits_NMDS)
# if stress tests are really low, there may be insufficient data.
# As a rule of thumb, an NMDS ordination with a stress value around or above 0.2 is deemed suspect and a stress value approaching 0.3 indicates that the ordination is arbitrary. 
#Stress values equal to or below 0.1 are considered fair, while 
#values equal to or below 0.05 indicate good fit.

#plot_df <- scores(seedbank_bysitecore_nmds, display = "sites") %>% # from An's code
#  as.data.frame() %>% 
#  rownames_to_column("stand_core") %>% 
#  full_join(seedbank_bysitecore, by = "stand_core")

nmds_leaftraits_df <- data.frame(leaftraits_NMDS$points, leaftraits) # code from chatgpt
view(nmds_leaftraits_df)
nmds_leaftraits_df <- nmds_leaftraits_df %>%
  rename("NMDS1" = "MDS1",
         "NMDS2" = "MDS2")
```

```{r ggplot leaf traits nmds}
nmds_leaftraits_df_plotcolor <- ggplot(nmds_leaftraits_df, aes(x = NMDS1, y = NMDS2, color = species)) + 
  geom_point(size = 3, alpha = 0.8, aes(shape = plant_rep)) +
  scale_color_manual(values = c("darkgreen", "darkmagenta", "darkgoldenrod1", "darkblue")) + # in color
 #scale_color_manual(values = c("gray0", "gray30", "gray60", "gray80")) + # in bw
  theme_bw() +
  theme(legend.position = c(0.08, 0.81)) + # x, y bottom left corner: 0,0
  stat_ellipse(level = .95, linetype = 1, linewidth = 1) + # linetype: 1 = solid, 2 = dashed
  labs(title = "NMDS: by leaf traits", color = "Species", shape = "Plant ID")

nmds_leaftraits_df_plotcolor

```

```{r nmds color and vectors with envfit function}
# code from An Bui: https://rpubs.com/an-bui/vegan-cheat-sheet 

nmds_leaftraits_vectors <- data.frame(leaftraits_NMDS$points, leaftraits_nmdsprep) # code from chatgpt. 
# Adds NMDS1 and NMDS2 to columns species, plant_rep, LSA, LDMC, and Leaf thickness

leaftraits_nmdsprep <- leaftraits_nmdsprep %>% 
  mutate(standtype_ID = seq(1,64, by = 1))

leaftraits_plotprep <- nmds_leaftraits_df %>%
  select(species, plant_rep, SLA_m2kg, leaf_LDMC_proportion, leaf_thickness_cm)

# add NMDS scores to pvalues
plot_leaftraits_df <- scores(leaftraits_NMDS, display = "sites") %>%
   as.data.frame()  %>%
   mutate(standtype_ID = seq(1,64, by = 1)) %>%
   # rownames_to_column("standtype_ID") %>%
   # mutate_at(c('standtype_ID'), as.numeric) %>%
   full_join(leaftraits_nmdsprep, by = "standtype_ID") %>%
   full_join(leaftraits_plotprep, by = c("SLA_m2kg", "leaf_LDMC_proportion", "leaf_thickness_cm")) %>%
   select(!c(standtype_ID))

# envfit() takes the output of metaMDS() and the species matrix you created
fit_leaftraits <- envfit(leaftraits_NMDS, leaftraits_nmdsprep_num, perm = 999) # pvalues for spp and stand, site, stand_core

# extract p-values for each species
fit_leaftraits_pvals <- fit_leaftraits$vectors$pvals %>% 
  as.data.frame() %>% 
  rownames_to_column("species") %>% 
  dplyr::rename("pvals" = ".")
# view(fit_leaftraits_pvals)

# extract coordinates for species, only keep species with p-val = 0.05
fit_leaftraits_nmdsscores <- fit_leaftraits %>% 
  scores(., display = "vectors") %>% 
  as.data.frame() %>% 
  rownames_to_column("species") %>% 
  # full_join(., fit_leaftraits_pvals, by = "species") %>% 
  # filter(pvals <= 0.05) %>% # limited number for visual clarity
  filter(!species == 'standtype_ID')
  
# view(fit_leaftraits_nmdsscores)
# new plot
nmds_leaftraits_df_plotcolor_new <- ggplot(plot_leaftraits_df, aes(x = NMDS1, y = NMDS2)) + 
  coord_equal() +
  geom_point(size = 3, alpha = 0.8, aes(color = species, shape = plant_rep)) +
  scale_color_manual(values = c("darkgreen", "darkmagenta", "darkgoldenrod1", "darkblue")) + # in color
 #scale_color_manual(values = c("gray0", "gray30", "gray60", "gray80")) + # in bw
 #theme(legend.position = c(0.08, 0.81)) + # x, y bottom left corner: 0,0 - IF want to set key within plot, otherwise sits outside figure
  stat_ellipse(level = .95, linetype = 1, linewidth = 1, aes(color = species)) + # linetype: 1 = solid, 2 = dashed
  geom_segment(data = fit_leaftraits_nmdsscores, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")),
               col = "black") +
    geom_text(data = fit_leaftraits_nmdsscores, aes(label = species),
              position = position_jitter(width = 0.1, height = 0.2)
             )+
  labs(title = "NMDS: by leaf traits", color = "Species", shape = "Plant ID")

nmds_leaftraits_df_plotcolor_new +  theme_bw()

```

```{r fortify nmds, include=FALSE}
#basic normal plot
#odiplot(leaftraits_NMDS) # without point labels
#ordiplot(leaftraits_NMDS, type = "t") # with point labels

#ggvegan to make a quick nice plot
#autoplot(seedbank_bysitecore_nmds) # NMDS1 x NMDS2, Key = "Score": sites, species
# sites == each leaf 
# species == leaf traits (leaf thickness, sla, dlmc)


#this makes a dataframe that gives a lot of control graphically 
#seedbank_bysitecore_nmds_fort <- fortify(seedbank_bysitecore_nmds)

#this makes a dataframe that gives a lot of control graphically 
#leaftraits_NMDS_fort <- fortify(leaftraits_NMDS)
```

```{r}
#this makes a dataframe that gives a lot of control graphically 
leaftraits_NMDS_fort <- fortify(leaftraits_NMDS) %>%
  left_join(nmds_leaftraits_df, by = c("NMDS1", "NMDS2"))

leaftraits_NMDS_fort[c(65,66,67), 5] = "value"

#dont mind me
grp.a <- leaftraits_NMDS_fort[leaftraits_NMDS_fort$species == "CEOL", ][chull(leaftraits_NMDS_fort[leaftraits_NMDS_fort$species == "CEOL", c("NMDS1", "NMDS2")]), ] 
grp.b <- leaftraits_NMDS_fort[leaftraits_NMDS_fort$species == "HEAR", ][chull(leaftraits_NMDS_fort[leaftraits_NMDS_fort$species == "HEAR", c("NMDS1", "NMDS2")]), ] 
grp.c <- leaftraits_NMDS_fort[leaftraits_NMDS_fort$species == "RHOV", ][chull(leaftraits_NMDS_fort[leaftraits_NMDS_fort$species == "RHOV", c("NMDS1", "NMDS2")]), ]  
grp.d <- leaftraits_NMDS_fort[leaftraits_NMDS_fort$species == "SAAP", ][chull(leaftraits_NMDS_fort[leaftraits_NMDS_fort$species == "SAAP", c("NMDS1", "NMDS2")]), ]  
hull.data <- rbind(grp.a, grp.b, grp.c, grp.d)  #combine grp.a and grp.b

#plot
 fortplot <-  ggplot() + 
  geom_point(data = subset(leaftraits_NMDS_fort, score == 'sites'),
             mapping = aes(x = NMDS1, y = NMDS2, color = species, shape = plant_rep),
             alpha = 0.5,  #transparency (to hide/show)
             show.legend = F) +
  geom_segment(data = fit_leaftraits_nmdsscores, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")),
               col = "black") +
  scale_color_manual(values = c("darkgreen", "darkmagenta", "darkgoldenrod1", "darkblue")) + 
  geom_polygon(data=hull.data,
               aes(x=NMDS1,y=NMDS2,fill=species,group=species),
               alpha=0.30,
               show.legend = F) +
  geom_text(data = fit_leaftraits_nmdsscores,
            mapping = aes(label = species, x = NMDS1*1.1, y = NMDS2*1.1),
            alpha = 0.5) + 
  geom_abline(intercept = 0,slope = 0,linetype = "dashed", linewidth = 0.8,colour = "gray")+
  geom_vline(aes(xintercept = 0), linetype = "dashed", linewidth = 0.8, colour = "gray")+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"))
  fortplot
ggplotly(fortplot)



leaf.hel <- decostand(leaftraits_nmdsprep_num, method = "hellinger")
nmdsC <- metaMDS(leaf.hel, autotransform = F, trymax = 20, k = 3)
nmdsD <- as.data.frame(fortify(nmdsC)) %>%
  rename("standtype_ID" = "label") %>%
  mutate_at(c('standtype_ID'), as.numeric) %>%
  full_join(leaftraits_nmdsprep, by = "standtype_ID") %>%
  full_join(leaftraits_plotprep, by = c("SLA_m2kg", "leaf_LDMC_proportion", "leaf_thickness_cm"))
leaf <- leaftraits
nmdsD
plot_ly(x=nmdsD$NMDS1, y=nmdsD$NMDS2, z=nmdsD$NMDS3, type="scatter3d", mode="markers", color = nmdsD$species)
plot_ly(x=nmdsD$NMDS1, y=nmdsD$NMDS2, mode="markers", color = nmdsD$species)
ggg <- plot_ly(x=leaf$SLA_m2kg, y=leaf$leaf_LDMC_proportion, z=leaf$leaf_thickness_cm, type="scatter3d", mode="markers", color = leaf$species) 

ggg %>%
  layout(
    xaxis = list(
      range=c(1,20), tick0=0.25, dtick=0.5),
    yaxis = list(
      range=c(1,20), tick0=0.25, dtick=0.5)
  )
```

