---
title: "Kit_graphs"
author: "Kit Swift"
date: "2022-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(lubridate)
library(readr)
library(plotly)
library(here)
```

```{r callin, include = FALSE}
surv_all <- read.csv("data/processed/surv_all.csv")
surv_all <- surv_all[,-1]
```

```{r base code, include=FALSE}
#Replace the following with what you want
#Y = Year to be looked at; M = month to be looked at; S = species to be looked at; plus any other filter
#GRAPHNAME = graph name; GRAPHDATA = dataset to be used to make graph
#GRAPHTITLE = Title on graph; XAXIS = xaxis label; YAXIS = Y axis label
#XVARIABLE = variable to be checked on x axis; YVARIABLE = variable to be checked on y axis; SORTBY = what regression lines you want

#GRAPHDATA <- surv_all %>% 
#  filter(year == "Y", 
#         month == "M", 
#         species == "S"
#         ) %>%
#  #group_by() %>%
#  #summarise_at(vars(r), funs(mean,sd))


#GRAPHNAME <- ggplot(
#  data = GRAPHDATA,
#  aes(x = XVARIABLE, y = YVARIABLE, color = SORTBY)) +
#  geom_point(size=2, shape=16) +
#  theme(legend.position="top") +
#  theme_classic() +
#  labs(title="GRAPHTITLE",x="XAXIS", y = "YAXIS") +
#  geom_smooth()
#ggplotly(GRAPHNAME)
```

```{r filter data}

# 2018 seedling survival by plot <-- need to calculate as percent of seedlings alive in month = 0
surv_18_byplot <- surv_all %>%
   filter(year == "2018") %>% 
  group_by(plot_number, month_count) %>% 
  summarise_at(vars(alive), list(sum,sd)) %>% 
  drop_na() %>% 
  rename(sum = fn1) %>% 
  rename(sd = fn2) %>% 
  mutate(plot_number = as.character(plot_number))

# 2018 seedling survival all
surv_18_all <- surv_18_byplot %>%
  group_by(month_count) %>% 
  summarise_at(vars(sum), list(mean,sd)) %>% 
  rename(mean = fn1) %>% 
  rename(sd = fn2)
view(surv_18_all)

# 2019 seedling survival by plot <-- need to calculate as percent of seedlings alive in month = 0
surv_19_byplot <- surv_all %>%
   filter(year == "2019") %>% 
  group_by(plot_number, month_count) %>% 
  summarise_at(vars(alive), list(sum,sd)) %>% 
  drop_na() %>% 
  rename(sum = fn1) %>% 
  rename(sd = fn2) %>% 
  mutate(plot_number = as.character(plot_number))

# 2019 seedling survival all
surv_19_all <- surv_19_byplot %>%
  group_by(month_count) %>% 
  summarise_at(vars(sum), list(mean,sd)) %>% 
  rename(mean = fn1) %>% 
  rename(sd = fn2)
view(surv_19_all)

```

```{r additional filter data, include=FALSE}
# 2019 seedling survival by plot 
survival_plot <- surv_all %>%
   filter(year == "2019"
  #        ,month == "M"
  #        ,species == "S"
  ) %>%
  group_by(plot_number, month_count) %>%
  summarise_at(vars(alive), funs(mean,sd))

# 2019 seedling survival by treatment 
survival_treatment <- surv_all %>%
   filter(year == "2019"
  #        ,month == "M"
  #        ,species == "S"
  ) %>%
  group_by(treatment, month_count) %>%
  summarise_at(vars(alive), funs(mean,sd))

```

```{r stats, include=TRUE}

# stats 2018 survival all
surv_18_all_aov <- aov(sum ~ month_count, data = surv_18_byplot)
summary(surv_18_all_aov)
# Df Sum Sq Mean Sq F value Pr(>F)    
#month_count   1   6106    6106   537.9 <2e-16 ***
#Residuals   142   1612      11  

# post-hoc

# stats 2019 survival all
surv_19_all_aov <- aov(sum ~ month_count, data = surv_19_byplot)
summary(surv_19_all_aov)
#Df Sum Sq Mean Sq F value Pr(>F)    
#month_count   1   2086  2086.5   412.9 <2e-16 ***
#Residuals   214   1082     5.1  

```

```{r initial seedlings, include = TRUE}
glimpse(surv_all)

#initial seedlings transplanted in January-February 2018 and January 2019
initial <- surv_all %>% 
  filter(year == "2018" & month == "1" | year == "2019" & month == "1") %>% 
  select("year", "plot_number", "species", "alive") %>% 
  rename(initial = alive)
  
view(initial)  
glimpse(initial)

# 2018
surv_all_prep <- surv_all %>%
  filter(year == "2018") %>% 
  dplyr::select("year", "month", "site", "plot_number", "treatment", "species", "alive")
unique(surv_all_prep$month)
surv_all_wider <- pivot_wider(surv_all_prep, 
                              names_from = month, 
                              values_from = alive) %>% 
  dplyr::select(!"4" & !"9") %>% 
  na.omit()

view(surv_all_wider)

surv_all_initial_2018 <- surv_all_wider %>% 
  left_join(initial, by = c("year", "plot_number", "species")) 
  
# convert months back to integers
surv_all_initial_2018 <- unnest(surv_all_initial_2018, cols = c("1", "2", "5", "12"))
write.csv(surv_all_initial_2018, "data/processed/surv_all_initial_2018.csv")

surv_2018_proportion <- read.csv("data/processed/surv_all_initial_2018_proportionalive.csv")
glimpse(surv_2018_proportion)

surv_2018_proportion_long <- surv_2018_proportion %>% 
  pivot_longer(cols = c('January_proportion', 'February_proportion', 'May_proportion', 'December_proportion'),
                    names_to='month_proportion',
                    values_to='proportion_alive')
view(surv_2018_proportion_long)

surv_2018_proportion_long_meanse <- surv_2018_proportion_long %>% 
   mutate(month_proportion = case_when(month_proportion == "December_proportion"~ "12",
                                        month_proportion == "February_proportion"~ "3", # March survival
                                        month_proportion == "January_proportion"~ "2", # initial survival in Jan-Feb
                                         month_proportion == "May_proportion"~ "5",
                               TRUE ~ month_proportion)) %>% 
  mutate(month_proportion = as.integer(month_proportion)) %>% 
  group_by(species, month_proportion) %>% 
  summarise(meanalive_2018 = mean(proportion_alive),
            SE = ((sd(proportion_alive))/sqrt(length((proportion_alive)))), 
             N = length(proportion_alive), 
             max = max(proportion_alive), # should be 1
              min = min(proportion_alive)) %>%  # should be 0 
    print(surv_2018_proportion_long_meanse)

# 2019
surv_all_prep_2019 <- surv_all %>%
  filter(year == "2019") %>% 
  dplyr::select("year", "month", "site", "plot_number", "treatment", "species", "alive") %>%
  mutate(month = case_when(month == 4 ~ 5,
                               TRUE ~ month))

unique(surv_all_prep_2019$month)
#[1]  1  3  5  6  7  9 11

surv_all_wider_2019 <- pivot_wider(surv_all_prep_2019, 
                              names_from = month, 
                              values_from = alive) %>% 
  dplyr::select(!"7") %>% 
  drop_na()

view(surv_all_wider_2019)
surv_all_wider_2019 %>% 
  group_by(plot_number) %>% 
  summarize(N = length(plot_number)) # all plots contain 4 species

surv_all_initial_2019 <- surv_all_wider_2019 %>% 
  left_join(initial, by = c("year", "plot_number", "species")) 
  
write.csv(surv_all_initial_2019, "data/processed/surv_all_initial_2019.csv")

surv_2019_proportion <- read.csv("data/processed/surv_all_initial_2019_proportionalive.csv")
glimpse(surv_2019_proportion)

surv_2019_proportion_long <- surv_2019_proportion %>% 
  pivot_longer(cols = c('jan_proportion', 'march_proportion', 'may_proportion', 'june_proportion',  'september_proportion', 'november_proportion'),
                    names_to='month_proportion',
                    values_to='proportion_alive') 

view(surv_2019_proportion_long)

surv_2019_proportion_long_meanse <- surv_2019_proportion_long %>% 
   mutate(month_proportion = case_when(month_proportion == "november_proportion"~ "11",
                                        month_proportion == "june_proportion"~ "5",
                                        month_proportion == "jan_proportion"~ "1",
                                         month_proportion == "may_proportion"~ "5",
                                         month_proportion == "march_proportion"~ "3",
                                        month_proportion == "september_proportion"~ "9",
                               TRUE ~ month_proportion)) %>% 
  mutate(month_proportion = as.integer(month_proportion)) %>% 
  group_by(species, month_proportion) %>% 
  summarise(meanalive_2019 = mean(proportion_alive),
            SE = ((sd(proportion_alive))/sqrt(length((proportion_alive)))), 
             N = length(proportion_alive), 
            max = max(proportion_alive), 
                  min = min(proportion_alive)) %>% 
  print(surv_2019_proportion_long_meanse)
```


```{r figures all seedlings by month and year}


# line: average survival by month 2018
line1_surv_18_all <- ggplot(
  data = surv_18_all,
  aes(x = month_count, y = mean)) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd)) +
  geom_line(aes()) + 
  geom_point(size=2, shape=16) +
  theme(legend.position="top") +
  theme_classic() +
  labs(title="Average seedling survival in 2018", x="Months Since Planting", y = "Mean number of alive seedlings (absolute)") 
  #geom_smooth()
ggplotly(line1_surv_18_all)

# line: average survival by month 2019
line1_surv_19_all <- ggplot(
  data = surv_19_all,
  aes(x = month_count, y = mean)) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd)) +
  geom_line(aes()) + 
  geom_point(size=2, shape=16) +
  theme(legend.position="top") +
  theme_classic() +
  labs(title="Average seedling survival in 2019", x="Months Since Planting", y = "Mean number of alive seedlings (absolute)") 
  #geom_smooth()
ggplotly(line1_surv_19_all)

```

```{r additional figures 2018 seedling survival, include=FALSE}

# survival by species 2018 - old code
survival_species_2018 <- ggplot(
  data = survival_species_2018,
  aes(x = month_count, y = mean, color = species)) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd)) +
  geom_line(aes(color = species, linetype = species)) + 
  geom_point(size=2, shape=16) +
  theme(legend.position="top") +
  theme_classic() +
  labs(title="survival_species in 2018",x="Months Since Planting", y = "Amount Alive") 
  #geom_smooth()
ggplot(survival_species_2018)

# 2018 survival by species - use this code
ggplot(data = surv_2018_proportion_long_meanse,
  aes(x = month_proportion, 
      y = meanalive_2018, 
      linetype = species, 
      fill = species)) +
  geom_line(aes(linetype = species), size = 1) + # color = species
   geom_point(size=4, shape=21) +
  geom_errorbar(aes(ymin=meanalive_2018-SE, ymax=meanalive_2018+SE), width = 0.2) +
  scale_y_continuous(limits = c(0, 1), 
                    breaks = seq(0, 1, by = 0.1)) +
  scale_x_continuous(limits = c(1, 12),
                     breaks = seq(1,12, by = 1), 
                      labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
  # scale_x_discrete(limits = (1:12),
  #                  labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
  theme(legend.position ="top") +
  theme_bw() +
 # scale_linetype_manual(values=species,
#                        name = "Species", 
#                        labels = c("Ceanothus oliganthus", "Heteromeles arbutifolia", "Rhus ovata", "Salvia apiana")) +
  labs(title="Proportion of alive seedlings in 2018", 
       x = "Month", 
       y = "Proportion Alive") 
  
```

```{r additional figures 2019 seedling survival, include=FALSE}
  
# survival by treatment 2019
survival_treatment_G <- ggplot(
  data = survival_treatment,
  aes(x = month_count, y = mean, color = treatment)) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd)) +
  geom_line(aes(color = treatment, linetype = treatment)) + 
  geom_point(size=2, shape=16) +
  theme(legend.position="top") +
  theme_classic() +
  labs(title="survival_treatment in 2019",x="Months Since Planting", y = "Amount Alive") 
  #geom_smooth()
ggplotly(survival_treatment_G)

survival_species_2018 <- surv_all %>%
   filter(year == "2018"
  #        ,month == "M"
  #        ,species == "S"
   ) %>%
  filter(month_count == "0" | month_count == "1" | month_count == "4" | month_count == "11" ) %>%  
  group_by(species, month_count) %>%
  summarise_at(vars(alive), funs(mean,sd))


# survival by species 2019
survival_species <- surv_all %>%
   filter(year == "2019"
  #        ,month == "M"
  #        ,species == "S"
   ) %>%
  group_by(species, month_count) %>%
  summarise_at(vars(alive), funs(mean,sd))

survival_species_G <- ggplot(
  data = survival_species,
  aes(x = month_count, y = mean)) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd)) +
  geom_line(aes(color = species, linetype = species)) + 
  geom_point(size=2, shape=16) +
  theme(legend.position="top") +
  theme_classic() +
  labs(title="survival_species in 2019",x="Months Since Planting", y = "Amount Alive") 
  #geom_smooth()
ggplotly(survival_species_G)

# 2019 survival by species - use this code 
ggplot(
  data = surv_2019_proportion_long_meanse,
  aes(x = month_proportion, 
      y = meanalive_2019, 
       linetype = species, 
      fill = species)) +
    geom_line(aes(linetype = species), size = 1) + # color = species
   geom_point(size=4, shape=21) +
  geom_errorbar(aes(ymin=meanalive_2019-SE, ymax=meanalive_2019+SE), width = 0.2) +
  scale_y_continuous(limits = c(0, 1), 
                    breaks = seq(0, 1, by = 0.1)) +
   scale_x_discrete(limits = 1:11,
                    labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
  theme(legend.position="top") +
  theme_bw() +
  labs(title="Proportion of alive seedlings in 2019", 
       x = "Month", 
       y = "Proportion Alive") 

```


```{r tdr scatterplot march 2019 and by mafa cover, test}
surv_all.2019 <- surv_all %>% 
  filter(year == "2019", month == "3")

tdr_cover_scatter_2019 <- ggplot(
  data = surv_all.2019,
  aes(x = cover_percent, y = soil_moisture, color = treatment)) +
  geom_point(size=2, shape=16) +
 # scale_color_manual(values=c('#D3E3CA', '#92A587', '#2F3525', '#9F7E75', '#B9B994', '#F19B34')) +
  theme(legend.position="top") +
  theme_classic() +
  labs(title="Soil Moisture by Treatment in March 2019",x="Canopy Cover (%)", y = "Soil Moisture (%)") +
  geom_smooth()
ggplotly(tdr_cover_scatter_2019)
```

``` {r tdr scatterplot march 2020 and by mafa cover, include=TRUE}
surv_all.2020 <- surv_all %>% 
  filter(year == "2020", month == "3")

tdr_cover_scatter_2020 <- ggplot(
  data = surv_all.2020,
  aes(x = cover_percent, y = soil_moisture, color = treatment)) +
  geom_point(size=2, shape=16) +
 # scale_color_manual(values=c('#D3E3CA', '#92A587', '#2F3525', '#9F7E75', '#B9B994', '#F19B34')) +
  theme(legend.position="top") +
  theme_classic() +
  labs(title="Soil Moisture by Treatment in March 2020",x="Canopy Cover (%)", y = "Soil Moisture (%)") +
  geom_smooth()

ggplotly(tdr_cover_scatter_2020)
```