---
title: "Piru_enchancement-Models"
author: "Kit Swift"
date: "2022-12-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here) # similar to set working directory
library(tidyverse) # data wrangling
library(lubridate) # dates and times
library(readr)
library(plotly)
library(dplyr)
library(olsrr)
library(survival)
library(lme4)
library(lmerTest)


#mafa_cover_all = MAFA % cover 2018 and 2019
#exotic_cover_all = exotic % cover 2018 and 2019


```

# Question 1: How do environmental conditions change by a) canopy treatment and b) canopy cover?
Is canopy treatment or canopy cover a stronger predictor of the environmental conditions below the shrub canopy? 

- Load data
```{r load data, include=TRUE}

# response variable: PAR
# explanatory variables: treatment, MAFA % cover, site
# data frame: combine par and mafa_cover_all

# Formula : a two-sided linear formula object describing both the fixed-effects and random effects part of the model,
# with the response on the left of a ~ operator and the terms, separated by + operators, on the right. 
# Random-effects terms are distinguished by vertical bars (|) separating expressions for design matrices from
# grouping factors. Two vertical bars (||) can be used to specify multiple uncorrelated random effects for the same
# grouping variable. (Because of the way it is implemented, the ||-syntax works only for design matrices containing
# numeric (continuous) predictors; to fit models with independent categorical effects, see dummy or the lmer_alt
# function from the afex package.)

# PAR
parmod <- par %>%
  left_join(mafa_cover_all, by = c("year", "site", "plot_number"), na.rm = F) %>% 
  rename(mafacover = cover_percent)
print(parmod)
write.csv(parmod, "data/processed/par_model.csv")

# TDR
tdrmod <- tdr %>% 
  left_join(mafa_cover_all, by = c("site", "plot_number"), na.rm = F) %>% 
  rename(year_tdr = year.x,
         year_mafacover = year.y,
         mafacover = cover_percent)
print(tdrmod)
write.csv(tdrmod, "data/processed/tdr_model.csv")

# NN COVER
nnmod <- exotic_cover_all %>% 
  left_join(mafa_cover_all, by = c("site", "plot_number"), na.rm = F) %>% 
  rename(year_nncover = year.x,
         year_mafacover = year.y,
         nncover = cover_percent.x,
         mafacover = cover_percent.y)
print(nnmod)
write.csv(nnmod, "data/processed/nn_model.csv")
  
```

```{r par model lme, include = TRUE}

lme.parmod <- lmer(normalized_par ~ treatment + mafacover + site + (1|date) +(1|plot_number),
                   data = parmod)

MOD <- lme.parmod

# Calculate model's residual and fitted values
F1 <- fitted(MOD)
E1 <- residuals(MOD, "pearson")

# See residuals as a histogram, look for normal distribution
hist(E1)

# Graph residuals against a normal distribution, look for all points to be on 1:1 line
#need to call next two lines together
qqnorm(E1, xlab = "Theoretical Quantiles", ylab = "Pearson Residuals")
qqline(E1)

# Graph residuals vs fitted values to inspect homogeneity of variance, look for a random scattering of plots
# run together 2 lines
plot(x=F1, y=E1, xlab="Fitted Model Values", ylab="Pearson Residuals", main = "Variance")
abline(h = 0) # looking for random scatter

# Check for crazy outliers, look for lines MUCH taller than the rest of data
plot(cooks.distance(MOD))

# Plot a box plot for each factor, look for equal variance amount levels along the zero line
# Box plots need to be assessed for every fixed effect (categorical factor) for your model. 
# Random effects need the qqline just like normality. 
# So, only site and treatment get box plots. 
# MAFA cover is a covariate (continuous variable).
boxplot(E1 ~ treatment, data = parmod)
abline(h = 0)

boxplot(E1 ~ site, data = parmod)
abline(h = 0)

# Plot each random effect in the model - things in the (1|_), look for dots along 1:1 line
qqnorm(ranef(MOD)$date[,1], main = "Plot Residuals")
qqline(ranef(MOD)$date[,1]) # unique dates

qqnorm(ranef(MOD)$plot_number[,1], main = "Plot Residuals")
qqline(ranef(MOD)$plot_number[,1]) # unique plots

# print 
print(lme.parmod)
summary(lme.parmod)
anova(lme.parmod)


parmodTest <- lmer(normalized_par ~ treatment + mafacover + site + (1|date) +(1|plot_number),
                   data = parmod)
# get Satterthwaite-approximated degrees of freedom
coefs$df.Satt <- coef(summary(parmodTest))[, 3]
# get approximate p-values
coefs$p.Satt <- coef(summary(parmodTest))[, 5]
coefs
```

```{r tdrmodel lme, include = TRUE}

lme.parmod <- lmer(normalized_par ~ treatment + mafacover + site + (1|date) +(1|plot_number),
                   data = parmod)

MOD <- lme.parmod

# Calculate model's residual and fitted values
F1 <- fitted(MOD)
E1 <- residuals(MOD, "pearson")

# See residuals as a histogram, look for normal distribution
hist(E1)

# Graph residuals against a normal distribution, look for all points to be on 1:1 line
#need to call next two lines together
qqnorm(E1, xlab = "Theoretical Quantiles", ylab = "Pearson Residuals")
qqline(E1)

# Graph residuals vs fitted values to inspect homogeneity of variance, look for a random scattering of plots
# run together 2 lines
plot(x=F1, y=E1, xlab="Fitted Model Values", ylab="Pearson Residuals", main = "Variance")
abline(h = 0) # looking for random scatter

# Check for crazy outliers, look for lines MUCH taller than the rest of data
plot(cooks.distance(MOD))

# Plot a box plot for each factor, look for equal variance amount levels along the zero line
# Box plots need to be assessed for every fixed effect (categorical factor) for your model. 
# Random effects need the qqline just like normality. 
# So, only site and treatment get box plots. 
# MAFA cover is a covariate (continuous variable).
boxplot(E1 ~ treatment, data = parmod)
abline(h = 0)

boxplot(E1 ~ mafacover, data = parmod)
abline(h = 0)

boxplot(E1 ~ site, data = parmod)
abline(h = 0)

# Plot each random effect in the model, look for dots along 1:1 line
qqnorm(ranef(MOD)$date[,1], main = "Plot Residuals")
qqline(ranef(MOD)$date[,1])

qqnorm(ranef(MOD)$plot_number[,1], main = "Plot Residuals")
qqline(ranef(MOD)$plot_number[,1])

# print 
print(lme.parmod)
summary(lme.parmod)
anova(lme.parmod)


parmodTest <- lmer(normalized_par ~ treatment + mafacover + site + (1|date) +(1|plot_number),
                   data = parmod)
# get Satterthwaite-approximated degrees of freedom
coefs$df.Satt <- coef(summary(parmodTest))[, 3]
# get approximate p-values
coefs$p.Satt <- coef(summary(parmodTest))[, 5]
coefs
```

```{r non-native cover model lme, include = TRUE}

lme.parmod <- lmer(normalized_par ~ treatment + mafacover + site + (1|date) +(1|plot_number),
                   data = parmod)

MOD <- lme.parmod

# Calculate model's residual and fitted values
F1 <- fitted(MOD)
E1 <- residuals(MOD, "pearson")

# See residuals as a histogram, look for normal distribution
hist(E1)

# Graph residuals against a normal distribution, look for all points to be on 1:1 line
#need to call next two lines together
qqnorm(E1, xlab = "Theoretical Quantiles", ylab = "Pearson Residuals")
qqline(E1)

# Graph residuals vs fitted values to inspect homogeneity of variance, look for a random scattering of plots
# run together 2 lines
plot(x=F1, y=E1, xlab="Fitted Model Values", ylab="Pearson Residuals", main = "Variance")
abline(h = 0) # looking for random scatter

# Check for crazy outliers, look for lines MUCH taller than the rest of data
plot(cooks.distance(MOD))

# Plot a box plot for each factor, look for equal variance amount levels along the zero line
# Box plots need to be assessed for every fixed effect (categorical factor) for your model. 
# Random effects need the qqline just like normality. 
# So, only site and treatment get box plots. 
# MAFA cover is a covariate (continuous variable).
boxplot(E1 ~ treatment, data = parmod)
abline(h = 0)

boxplot(E1 ~ mafacover, data = parmod)
abline(h = 0)

boxplot(E1 ~ site, data = parmod)
abline(h = 0)

# Plot each random effect in the model, look for dots along 1:1 line
qqnorm(ranef(MOD)$date[,1], main = "Plot Residuals")
qqline(ranef(MOD)$date[,1])

qqnorm(ranef(MOD)$plot_number[,1], main = "Plot Residuals")
qqline(ranef(MOD)$plot_number[,1])

# print 
print(lme.parmod)
summary(lme.parmod)
anova(lme.parmod)


parmodTest <- lmer(normalized_par ~ treatment + mafacover + site + (1|date) +(1|plot_number),
                   data = parmod)
# get Satterthwaite-approximated degrees of freedom
coefs$df.Satt <- coef(summary(parmodTest))[, 3]
# get approximate p-values
coefs$p.Satt <- coef(summary(parmodTest))[, 5]
coefs
```

```{r checking for normality - by treatment, include = TRUE}
# Testing for normality
# In general, if you have less than 50 observations, you should use the Shapiro-Wilk test. 
# Otherwise, the Kolmogorov-Smirnov test is better.

# TDR, PAR, and exotic cover by treatment
model1 <- lm(soil_moisture + normalized_par + exotic_cover ~ treatment, data=surv_all)
e <- residuals(model1, type="pearson")
f <- fitted(model1)

# qq plot
qqnorm(e)
qqline(e)

qqnorm(f)
qqline(f)
```
```{r checking for normality - by native cover, include = TRUE}

# TDR, PAR, and exotic cover by native percent cover
model2 <- lm(soil_moisture + normalized_par + exotic_cover ~ native_cover, data=surv_all)
g <- residuals(model2, type="pearson")
h <- fitted(model2)

# qq plot
qqnorm(g)
qqline(g)

qqnorm(h)
qqline(h)
```



```{r , include = TRUE}
ols_test_normality(model1)


shapiro.test(surv_all$native_cover)
shapiro.test(surv_all$exotic_cover)



hist(surv_all$native_cover, col='steelblue')

model1 <- lm(treatment ~ normalized_par, data=surv_all)






model <- lm( ~ disp + hp + wt + qsec, data = mtcars)

k.test(surv_all$exotic_cover)
pnorm
plot(surv_all$native_cover ~ surv_all$normalized_par)
```


```{r checking for normality, include = TRUE}
# Check for normality and heteroskedasticity <-- FROM AUSTEN
par(mfrow=c(2,2)) 
plot(model.presence.sh)
shapiro.test(model.presence.sh$residuals)
ggplot(data = NULL, aes(x = model.presence.sh$residuals)) + geom_density(aes(y=..scaled..))
car::leveneTest(sh.dat.samples.pa$sh, sh.dat.samples.pa$Quadrat.Identifier, center = median)
#https://easystats.github.io/performance/
```


```{r}
#Initial! 
#Wrong!

# GRAPHDATA <- surv_all %>% 
#     group_by(treatment, month_count, species) %>%
#     summarise_at(vars(alive), funs(mean,sd))



m0 <- lm(alive ~ species + soil_moisture + normalized_par, data=surv_all)
m00 <- lm(alive ~ species + year + month, data=surv_all)
m1 <- lm(alive ~ soil_moisture + normalized_par, data=surv_all)
m3 <- lm(alive ~ cover_percent + soil_moisture + normalized_par + species, data=surv_all)
m4 <- lm(alive ~ treatment + soil_moisture + normalized_par + species, data=surv_all)

anova(m0)
anova(m1)
anova(m3)
anova(m5)

################## a) are the residuals normal? b) 
plot(m00) # viewing residuals... i think...
hist(m00$residuals, main = "Residual Historgram: m0") # histogram of residuals
ols_plot_resid_hist(m00)
boxplot(m00$residuals, main = "Residual Box Plot: m0") # box plot of residuals

# Testing for normality
# In general, if you have less than 50 observations, you should use the Shapiro-Wilk test. 
# Otherwise, the Kolmogorov-Smirnov test is better.
ols_test_normality(m00)


```

```{r}

m_Envsitemafa <- lmer((Par, TDr, nn%) ~ MAFA treatment * site, data = surv_all)
m_Envsitepc <- lmer((Par, TDr, nn%) ~ percent cover * site, data = surv_all)

m_alive <- lmer(alive ~ myvars + year + month + site + random(1/plot), data = surv_all)

```