---
title: "ch3 SAAP and HEAR survival - November 2019"
author: "Stephanie Ma Lucero"
date: "`r Sys.Date()`"
output: html_document
---

# load library
```{r load libraries, message=FALSE}
library(here) # similar to set working directory
library(dplyr) # includes functions:
library(tidyverse) # data wrangling, includes packages: ggplot2, tibble, tidyr, rear, purrr, stringr, forcats
library(ggpubr)
```

```{r load data, include=FALSE}
nov <- read_csv("data/Nov2019_HEARSAAPsurvival.csv", 
    col_types = cols(
      Species = col_character(), 
      Site = col_factor(),
      Treament = col_character(), 
      Month = col_character(),
      Alive = col_integer()
      )
    ) %>% 
  rename(Treatment = Treament) 

```

```{r hear plot}
nov2 <- nov %>% 
  group_by(Month) %>% 
  mutate(ind = 1:length(Month))

nov_fig <- ggplot(nov2, 
       aes(x=Month, 
           y=Alive,
           shape = Site,
           color = Site,
           linetype = Treatment,
           group=ind))+
  geom_line(size = 1)+
  geom_point(size = 3) +
  scale_y_continuous(limits = c(0, 22), 
                    breaks = seq(0, 22, by = 2)) +
  scale_shape_manual(values = c(3, 4)) +
    scale_color_manual(values = c("black", "gray50"),
                     name = "Site",
                     labels = c("1", "2")) +
  scale_linetype_manual(values = c("solid", "dashed", "dotted"),
                        name = "Treatment",
                        labels = c("No removal", "Half removal", "Full removal")) + 
  theme_bw() +
 facet_wrap(~ Species) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        legend.position = "right") +
  labs(title = "Seedling Survival from April to November 2019",
       x = "Month",
       y = "Number of alive seedlings (#)")

#ggsave("figures/alivenov2019.png", nov_fig, width = 8, height = 4)
```



















