---
title: "ch3 Site Differences - pre-removal"
author: "Stephanie Ma Lucero"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load library
```{r load libraries, message=FALSE}
library(here) # similar to set working directory
library(dplyr) # includes functions:
library(tidyverse) # data wrangling, includes packages: ggplot2, tibble, tidyr, rear, purrr, stringr, forcats
library(ggpubr)

# for pretty output tables
install.packages("kableExtra")
# For dev version
# install.packages("devtools")
devtools::install_github("haozhu233/kableExtra")
library(kableExtra)
```

- load data
```{r nn load, include=TRUE}
# load total_exotic percent cover data as a .csv
nncover_noremoval_load <- read_csv("data/totexo_cover.csv", 
    col_types = cols(
      date = col_character(), 
      year = col_character(),
      plot_number = col_integer(), 
      cover_percent = col_number(),
      notes = col_character()
      )
    )

nncover_noremoval <- nncover_noremoval_load %>% 
  rename(treatment = MAFA_removal) %>% 
  rename(nn_cover = cover_percent) %>% 
  mutate(site = case_when(plot_number <= 18 ~ '1', plot_number >= 19 ~ '2')) %>% 
  dplyr::filter(year %in% c(2018, 2019)) %>% 
  dplyr::filter(treatment == "none") %>% 
  dplyr::select(year, treatment, site, plot_number, nn_cover) 

#view(nncover_noremoval)
head(nncover_noremoval)

#str(nncover_noremoval)
print(nncover_noremoval)
length(nncover_noremoval$site)
```

# Overall site differences

## - non-native cover
- Data is located in --> "Processed" data folder

```{r nn norm, include = TRUE}
# nn percent cover by site
hist(nncover_noremoval$nn_cover)
ggqqplot(nncover_noremoval$nn_cover)
shapiro.test(nncover_noremoval$nn_cover)
# Shapiro-Wilk normality test
# 
# data:  nncover_noremoval$cover_percent
# W = 0.98116, p-value = 0.9162 <-- normally distributed
```

```{r nn stats, include=TRUE}
nncover_aov <- aov(nn_cover ~ site, data= (nncover_noremoval))
summary(nncover_aov)
#             Df Sum Sq Mean Sq F value Pr(>F)
# site         1    376   376.4   2.545  0.125
# Residuals   22   3255   147.9  
# 
# 2017 pval = 0.123
# 2018 pval = 0.688
# 2019 pval = 0.101
# 2018-2019 pval = 0.125

nncover_table <- nncover_noremoval %>%  
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_nncover = mean(nn_cover), 
            SD = sd(nn_cover),
            N = length(nn_cover), 
            SE = ((sd(nn_cover))/sqrt(length((nn_cover)))))
# site  avg_nncover SD        N   SE
# 1	    32.03750  	12.46517	12	3.598385
# 2   	39.95833  	11.85279	12	3.421605

### print in Console
nncover_table %>%
  dplyr::select(site, avg_nncover, SE, N) %>%
 kbl(caption = "Non-native cover by site", digits = 1) %>%
 kable_classic(full_width = F, html_font = "Cambria")
```



## - MAFA cover
```{r load mafa cover, include=TRUE}

mafa_cover_noremoval <- read_csv("data/mafa_cover.csv", 
    col_types = cols(
      date = col_character(), 
      year = col_integer(),
      plot_number = col_integer(), 
      MAFA_removal = col_character(),
      cover_type = col_character(),
      cover_percent = col_number(), # question for SHANE - Percent cover as number or integer?
      notes = col_character()
      )
    ) %>% 
   dplyr::select(year, plot_number, MAFA_removal, cover_percent) %>% 
   mutate(site = case_when(plot_number <= 18 ~ '1', plot_number >= 19 ~ '2')) %>% 
   rename(mafacover = cover_percent) %>% 
   rename(treatment = MAFA_removal) %>% 
  mutate(site = as.character(site)) %>% 
   dplyr::filter(year %in% c(2018, 2019)) %>% 
   dplyr::filter(treatment == "none")
  
#view(mafa_cover_noremoval)
#str(mafa_cover_noremoval)
print(mafa_cover_noremoval)
length(mafa_cover_noremoval$site)
```

```{r mafa_cover differences - normality, include=TRUE}
# mafacover by site
hist(mafa_cover_noremoval$mafacover)
ggqqplot(mafa_cover_noremoval$mafacover)
shapiro.test(mafa_cover_noremoval$mafacover)
# Shapiro-Wilk normality test
# 
# data:  mafa_cover_noremoval$mafacover
# W = 0.96348, p-value = 0.5121 <-- normally distributed
```
### - 2018 - 2019
```{r mafa_cover differences - stats, include=TRUE}
mafacover_aov <- aov(mafacover ~ site, data= (mafa_cover_noremoval))
summary(mafacover_aov)
# Df Sum Sq Mean Sq F value Pr(>F)   
# site         1   3349    3349   13.35 0.0014 ** <-- sig different
# Residuals   22   5520     251   

mafacover_table <- mafa_cover_noremoval %>%  
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_mafacover = mean(mafacover), 
            SD = sd(mafacover),
            N = length(mafacover), 
            SE = ((sd(mafacover))/sqrt(length((mafacover)))))
# site      avg_mafacover    SD     N    SE
# 1              44.3       15.6    12  4.50
# 2              20.7       16.1    12  4.64

### print in Console
mafacover_table %>%
  dplyr::select(site, avg_mafacover, SE, N) %>%
 kbl(caption = "MAFA cover by site", digits = 1) %>%
 kable_classic(full_width = F, html_font = "Cambria")

```

### - 2018
```{r mafa_cover differences - stats, include=TRUE}
mafacover_aov <- aov(mafacover ~ site, data = mafa_cover_noremoval %>% filter(year == "2018"))
summary(mafacover_aov)
# Df Sum Sq Mean Sq F value Pr(>F)   
# site         1  963.0   963.0   13.85 0.00396 ** <-- sig different
# Residuals   22   5520     251   

mafacover_table_2018 <- mafa_cover_noremoval %>%  
  filter(year == "2018") %>% 
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_mafacover = mean(mafacover), 
            SD = sd(mafacover),
            N = length(mafacover), 
            SE = ((sd(mafacover))/sqrt(length((mafacover)))))
#  site  avg_mafacover    SD     N    SE
# 1 1              34    7.38     6  3.01
# 2 2              16.1  9.20     6  3.76

### print in Console
mafacover_table_2018 %>%
  dplyr::select(site, avg_mafacover, SE, N) %>%
 kbl(caption = "MAFA cover in 2018 by site", digits = 1) %>%
 kable_classic(full_width = F, html_font = "Cambria")

```


### - 2019
```{r mafa_cover differences - stats, include=TRUE}
mafacover_aov <- aov(mafacover ~ site, data = mafa_cover_noremoval %>% filter(year == "2019"))
summary(mafacover_aov)
# Df Sum Sq Mean Sq F value Pr(>F)   
# site         1   2581  2581.3   7.854 0.0187 *** <-- sig different


mafacover_table_2019 <- mafa_cover_noremoval %>%  
  filter(year == "2019") %>% 
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_mafacover = mean(mafacover), 
            SD = sd(mafacover),
            N = length(mafacover), 
            SE = ((sd(mafacover))/sqrt(length((mafacover)))))
#  site  avg_mafacover    SD     N    SE
# 1 1              54.7  15.0     6  6.12
# 2 2              25.3  20.8     6  8.49

### print in Console
mafacover_table_2019 %>%
  dplyr::select(site, avg_mafacover, SE, N) %>%
 kbl(caption = "MAFA cover in 2019 by site", digits = 1) %>%
 kable_classic(full_width = F, html_font = "Cambria")

```

```{r nngrass cover differences - normality, include=TRUE}
# mafacover by site
hist(exotic_cover_all$cover_percent)
ggqqplot(exotic_cover_all$cover_percent)
shapiro.test(exotic_cover_all$cover_percent)
# Shapiro-Wilk normality test
# 
# data:  exotic_cover_all$cover_percent
# W = 0.96645, p-value = 0.05159 <-- normally distributed!!!
```

## - MAFA density 
Data collected in 2020.
```{r mafa density load}
density <- read_csv("data/mafa_density_circumf.csv",
                         col_types = cols(
                           date = col_character(), 
                           standtype = col_character(),
                           site = col_character(), 
                           plot = col_integer(), 
                           removal = col_character(),
                           MAFA_density = col_integer()
                           )
                         ) %>% 
  dplyr::select(site, plot, removal, MAFA_density) %>% 
  na.omit() %>% 
  rename(treatment = removal) %>% 
  dplyr::filter(treatment == "no") 


#view(density)
```


```{r mafa_density - normality, include=TRUE}
# mafa_density by site
hist(density$MAFA_density)
ggqqplot(density$MAFA_density)
shapiro.test(density$MAFA_density)
# Shapiro-Wilk normality test
# 
# data:  density$MAFA_density
# W = 0.6286, p-value = 0.0001878 <-- not normally distributed
```

```{r density - stats, include=TRUE}
wilcox.test(MAFA_density ~ site, data=density) 
#Wilcoxon rank sum test with continuity correction
#
# data:  MAFA_density by site
# W = 28, p-value = 0.1249 <-- not sig different
# alternative hypothesis: true location shift is not equal to 0


density_table <- density %>%  
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_mafadensity = mean(MAFA_density), 
            SD = sd(MAFA_density),
            N = length(MAFA_density), 
            SE = ((sd(MAFA_density))/sqrt(length((MAFA_density)))))
# site        avg_mafadensity    SD     N     SE
# 1                 22.5        27.4    6     11.2 
# 2                 4.83        4.17    6     1.70


### print in Console
density_table %>%
  dplyr::select(site, avg_mafadensity, SE, N) %>%
 kbl(caption = "MAFA density by site", digits = 1) %>%
 kable_classic(full_width = F, html_font = "Cambria")

```

## - TDR
```{r}

tdr_site <- read.csv(here("data/processed", "tdr.csv")) %>% 
  mutate(treatment = case_when(treatment == "nonene" ~ "none", 
         TRUE ~ treatment))

hist(tdr_site$soil_moisture)
ggqqplot(tdr_site$soil_moisture)
shapiro.test(tdr_site$soil_moisture) # <-- not normally distributed, p-value = 2.254e-09

```

### - 2018 - 2019
```{r}
################### 2018 and 2019
wilcox.test(soil_moisture ~ site, data = tdr_site) 
# ata:  soil_moisture by site
# W = 7882.5, p-value = 8.056e-06 <-- sig diff

tdr_table <- tdr_site %>%  
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_TDR = mean(soil_moisture), 
            SD = sd(soil_moisture),
            N = length(soil_moisture), 
            SE = ((sd(soil_moisture))/sqrt(length((soil_moisture)))))
#   site avg_TDR    SD     N    SE
# 1     1    20.8  7.77   108 0.748
# 2     2    16.7  7.49   108 0.721


### print in Console
tdr_table %>%
  dplyr::select(site, avg_TDR, SE, N) %>%
 kbl(caption = "Soil Moisture by site", digits = 1) %>%
 kable_classic(full_width = F, html_font = "Cambria")
```

### - 2018
```{r}
################### 2018 
wilcox.test(soil_moisture ~ site, data = tdr_site %>%  filter(year == "2018")) 

tdr_table_2018 <- tdr_site %>%  
  filter(year == "2018") %>% 
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_TDR = mean(soil_moisture), 
            SD = sd(soil_moisture),
            N = length(soil_moisture), 
            SE = ((sd(soil_moisture))/sqrt(length((soil_moisture)))))


### print in Console
tdr_table_2018 %>%
  dplyr::select(site, avg_TDR, SE, N) %>%
 kbl(caption = "Soil Moisture by site", digits = 1) %>%
 kable_classic(full_width = F, html_font = "Cambria")
```

### - 2019
```{r}
################### 2019 
wilcox.test(soil_moisture ~ site, data = tdr_site %>%  filter(year == "2019")) 

tdr_table_2019 <- tdr_site %>%  
  filter(year == "2019") %>% 
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_TDR = mean(soil_moisture), 
            SD = sd(soil_moisture),
            N = length(soil_moisture), 
            SE = ((sd(soil_moisture))/sqrt(length((soil_moisture)))))


### print in Console
tdr_table_2019 %>%
  dplyr::select(site, avg_TDR, SE, N) %>%
 kbl(caption = "Soil Moisture by site", digits = 1) %>%
 kable_classic(full_width = F, html_font = "Cambria")
```


## - PAR
```{r}
par_site <- read.csv(here("data/processed", "par.csv")) 

hist(par_site$normalized_par)
ggqqplot(par_site$normalized_par)
shapiro.test(par_site$normalized_par) # <-- not normally distributed, p-value = 0.0005271
 
```


### - 2018 - 2019
```{r}
################### 2018 and 2019
wilcox.test(normalized_par ~ site, data = par_site) 
# W = 7119, p-value = 4.289e-06 <-- sig diff

par_table <- par_site %>%  
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_normPAR = mean(normalized_par), 
            SD = sd(normalized_par),
            N = length(normalized_par), 
            SE = ((sd(normalized_par))/sqrt(length((normalized_par)))))

### print in Console
par_table %>%
  dplyr::select(site, avg_normPAR, SE, N) %>%
 kbl(caption = "Normalized PAR by site", digits = 3) %>%
 kable_classic(full_width = F, html_font = "Cambria")
```

### - 2018
```{r}
################### 2018 
wilcox.test(normalized_par ~ site, data = par_site %>% filter(year == "2018")) # <- not sig

par_table_2018 <- par_site %>%  
  filter(year == "2018") %>% 
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_normPAR = mean(normalized_par), 
            SD = sd(normalized_par),
            N = length(normalized_par), 
            SE = ((sd(normalized_par))/sqrt(length((normalized_par)))))

### print in Console
par_table_2018 %>%
  dplyr::select(site, avg_normPAR, SE, N) %>%
 kbl(caption = "Normalized PAR in 2018 by site", digits = 3) %>%
 kable_classic(full_width = F, html_font = "Cambria")
```

### - 2019
```{r}
################### 2019 
wilcox.test(normalized_par ~ site, data = par_site %>% filter(year == "2019")) # <-  sig

par_table_2019 <- par_site %>%  
  filter(year == "2019") %>% 
  dplyr::group_by(site) %>% 
  dplyr::summarize(avg_normPAR = mean(normalized_par), 
            SD = sd(normalized_par),
            N = length(normalized_par), 
            SE = ((sd(normalized_par))/sqrt(length((normalized_par)))))

### print in Console
par_table_2019 %>%
  dplyr::select(site, avg_normPAR, SE, N) %>%
 kbl(caption = "Normalized PAR in 2019 by site", digits = 3) %>%
 kable_classic(full_width = F, html_font = "Cambria")
```
