---
title: "survival"
author: "Stephanie Ma Lucero"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here) # similar to set working directory
library(tidyverse) # data wrangling
library(lubridate) # dates and times
library(ggplot2)
```

```{r view normalized par, include=TRUE}
print(survival)
```
Testing the survival dataset for normality
```{r survival test for normality}
survival_normality <- ggplot(survival) + geom_histogram(aes(x = alive))
print(survival_normality)

# not normally distributed
```

Calculate the mean and standard errors of survival by ENH treatment.
```{r norm_survival mean and SD by treatment}
survival_meanSD <- survival %>%
  group_by(treatment, year, month) %>% # to graph by ENH treatment
  summarise_at(vars(alive), funs(mean,sd)) 
 
print(survival_meanSD)
```

```{r 2018 survival, include=TRUE}

survival_meanSD_2018 <- 

```


```{r survival line graph by month and by treatment, include=TRUE, echo=FALSE}
survival_line <- ggplot(data = survival_meanSD, aes(x = month, y = mean, group=MAFA_removal)) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
  position = position_dodge(0.05)) +
  geom_line(aes(color = MAFA_removal, linetype = MAFA_removal)) +
  geom_point()+
  scale_color_manual(values=c('#F19B34', '#D3E3CA', '#9F7E75')) +
  theme_classic() +
  labs(title="Survival",x="Month", y = "Alive (n)")

print(survival_line)
```

```{r survival scatterplot by month and by soil moisture, include=TRUE}
survival.2019 <- survival_soil_moisture %>% 
  filter(year =="2019" | year == "2020")  

survival_soilmoisture_scatter.2019 <- ggplot(
 data = survival.2019,
  aes(x = soil_moisture, y = alive, color = month)) +
  geom_point(size=2, shape=16) +
 # scale_color_manual(values=c('#D3E3CA', '#92A587', '#2F3525', '#9F7E75', '#B9B994', '#F19B34')) +
  theme(legend.position="top") +
  theme_classic() +
  labs(title="Seedling survival 2019-2021",x="Soil Moisture (%)", y = "Total seedling survival (#)")

print(survival_soilmoisture_scatter.2019)
```


```{r}
print(survival_mafacover.2018)
```
```{r survival_all.2018, include=TRUE}
survival_all.2018 <- survival_mafacover.2018 %>% 
  group_by(plot_number, month.survival, year.survival, cover_percent, year.MAFAcover) %>% 
  summarise(alive_total = sum(alive, na.rm = TRUE)) %>% 
  filter(plot_number < 11 | plot_number > 18) # <-- omitting plots 11 - 18 because two data collections in one month

print(survival_all.2018)
```
```{r survival_all.2018_scatter, include=TRUE, echo=FALSE}
survival_all.2018_scatter <- ggplot(survival_all.2018, aes(x=month.survival, y=cover_percent, color = alive_total)) + 
  geom_point() +
  scale_colour_gradient(high = "green")+
ylim(0, 100) +
xlim(1, 12) +
labs(title = "2018 Seedling Survival") +
ylab("MAFA Cover (%)") +
xlab("Month of 2018")
  

print(survival_all.2018_scatter)
```
```{r survival_all.2019, include=TRUE}
survival_all.2019 <- survival_mafacover.2019 %>% 
  group_by(plot_number, month.survival, year.survival, cover_percent, year.MAFAcover) %>% 
  summarise(alive_total = sum(alive, na.rm = TRUE))
#  filter(plot_number < 11 | plot_number > 18) # <-- omitting plots 11 - 18 because two data collections in one month

print(survival_all.2019)
```


```{r survival_all.2019_scatter, include=TRUE, echo=FALSE}
survival_all.2019_scatter <- ggplot(survival_all.2019, aes(x=month.survival, y=cover_percent, color = alive_total)) + 
  geom_point() +
    scale_colour_gradient(high = "green")+
ylim(0, 100) +
xlim(1, 12) +
labs(title = "2019 Seedling Survival") +
ylab("MAFA Cover (%)") +
xlab("Month of 2019")

print(survival_all.2019_scatter)
```

```{r survival_species.2019, include=TRUE}
survival_species.2019_all <- survival_mafacover.2019 %>% 
  group_by(species, month.survival, year.survival, cover_percent, year.MAFAcover) %>% 
  summarise(alive_total = sum(alive, na.rm = TRUE))
# filter(plot_number < 11 | plot_number > 18) # <-- omitting plots 11 - 18 because two data collections in one month

print(survival_species.2019_all)
```



```{r survival_species.2019_CEOL_scatter, include=TRUE, echo=FALSE}

survival_species.2019_CEOL <- survival_species.2019_all %>% 
  filter(species == "CEOL")

survival_species.2019_CEOL_scatter <- ggplot(survival_species.2019_CEOL,
                                             aes(x=month.survival, y=cover_percent, color = alive_total)) + 
  geom_point() +
  scale_colour_gradient(high = "green")+
ylim(0, 100) +
xlim(1, 12) +
labs(title = "2019 CEOL Survival") +
ylab("MAFA Cover (%)") +
xlab("Month of 2019")
  

print(survival_species.2019_CEOL_scatter)
```

```{r survival_species.2019_SAAP_scatter, include=TRUE, echo=FALSE}

survival_species.2019_SAAP <- survival_species.2019_all %>% 
  filter(species == "SAAP")

survival_species.2019_SAAP_scatter <- ggplot(survival_species.2019_SAAP,
                                             aes(x=month.survival, y=cover_percent, color = alive_total)) + 
  geom_point() +
  scale_colour_gradient(high = "green")+
ylim(0, 100) +
xlim(1, 12) +
labs(title = "2019 CEOL Survival") +
ylab("SAAP Cover (%)") +
xlab("Month of 2019")
  

print(survival_species.2019_SAAP_scatter) # <- multiple plots have 0% MAFA cover resulting in 12 SAAPs 
```
